# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     get_fixed_atom_index
   Description :
   Author :       DrZ
   date：          2021/3/31
-------------------------------------------------
   Change Activity:
                   2021/3/31:
-------------------------------------------------
"""
import sys
import numpy as np
from vaspy.atomco import PosCar

"""
Usage: python get_fixed_atom_indice.py POSCAR
Note: POSCAR must be produced by xsd2pos, and should contain TF information generated by material studio
"""
def output(ilist):
    amin=np.min(ilist)
    amax=np.max(ilist)
    indice = []
    for n, i in enumerate(ilist):
        if n == 0:
            continue
        if int(i) - int(ilist[n-1]) != 1:
            indice.append(ilist[n-1])
            indice.append(i)
    if not indice:
        indice.append(amin)
        indice.append(amax)
    if indice[-1] != amax:
        indice.append(amax)
    if indice[0] != amin:
        indice.insert(0, amin)
    return indice


if __name__ == '__main__':
    args = sys.argv
    path = args[1]
    pos = PosCar(path)
    coor = pos.dir2cart(pos.bases, pos.data)
    indice_list = []
    for i in range(len(pos.tf)):
        if pos.tf[i][0] == 'F':
            indice_list.append(i+1)
    out = output(indice_list)
    print('Index of fix atom (start from 1)')
    print(indice_list)
    print('Omit:', out)
