#!/bin/bash
#########################################################################
# File Name: /data/home/wdhu/script/la.sh
# Author: wdhu@59.78.92.45
# Created Time: Wed 06 Aug 2014 08:06:10 PM CST
#########################################################################
if [  x$1 == x ]; then
	outfile=OUTCAR
else
	outfile=$1
fi
#echo $outfile
echo LAST FORCES
F=$(printf "%.4f" `cat $outfile 2>/dev/null |grep -a RMS |uniq|tail -1 |awk '{print $5 }'`)
if [ $(echo "$F <= 0.05 && $F > 0 "|bc) = 1  ]
then
	printf "\033[32m%.4f\033[0m\n" $F
elif [ $(echo "$F < 0.1 && $F > 0.05 "|bc) = 1  ]
then
	printf "\033[1;31m%.4f\033[0m\n" $F
	mF=$(printf "%.4f" `cat  $outfile 2>/dev/null | grep -a RMS |uniq | awk '{print $5}' | sort -n | head -1` )
	mStep=$(printf "%s" `cat  $outfile 2>/dev/null | grep -a RMS |uniq | cat -n | sort -n -k 6 | awk '{print $1}' | head -1`)
	printf "\033[1;31m%.4f(min)\033[36m@(%s)\033[0m\n" $mF  $mStep
else
	printf "\033[31m%.4f\033[0m\n" $F
	mF=$(printf "%.4f" `cat $outfile 2>/dev/null|grep -a RMS |uniq | awk '{print $5}' | sort -n | head -1` )
	mStep=$(printf "%s" `cat  $outfile 2>/dev/null | grep -a RMS |uniq | cat -n | sort -n -k 6 | awk '{print $1}' | head -1`)
	if [ $(echo "$mF < 0.1 && $mF > 0.05 "|bc) = 1  ]
	then
		printf "\033[1;31m%.4f(min)\033[36m@(%s)\033[0m\n" $mF  $mStep
	elif [ $(echo "$mF > 0.1 "|bc) = 1  ]
	then
		printf "\033[31m%.4f(min)\033[36m@(%s)\033[0m\n" $mF  $mStep
	fi
fi
echo LAST ENERGY
printf "\033[1;33m%.4f\n\033[0m" `grep -a 'energy(sigma->0)' $outfile 2>/dev/null |tail -1|awk -F \= '{print $3}'`
echo TOTAL MAG
#printf "\033[1;35m  %.2f\n\033[0m"  `grep -a magnetization $outfile 2>/dev/null | grep -a "number of electron" |tail -1|awk '{print $6}'`
printf "\033[1;35m  %.2f\n\033[0m"  `grep -a "number of electron" $outfile 2>/dev/null |tail -1|awk '{print $6+0 }'`
